language: node_js
node_js:
  - "10"

branches:
  only:
  - master
  - /.*/
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:
- npm test
- npm run coveralls
deploy:
  provider: npm
  email: "armandjanssen1978@gmail.com"
  api_key: "$NPM_TOKEN"
  on: 
    tags: true